[package]
name = "concurrent-hashmap"
version = "0.0.2"
authors = ["Viktor Dahl <pazaconyoman@gmail.com>"]

[dependencies]
spin = '0.3'

[dev-dependencies]
rand = '0.3.11'

[profile.test]
opt-level = 1

[profile.bench]
debug = true
